set more off
clear all
set matsize 11000
set maxvar  32000
set seed 0
global bootstraps 500

// set environment variables
global projects: env projects
global storage : env storage

// locations
global data = "$storage/econ900/econ900-03/final"

cd  $data
use lottery_newstata.dta, clear

// 1. 
// group year and category 
egen clus = group(year lotcateg)

reg  d z, cluster(clus)
matrix bfirststage = e(b)
matrix bfirststage = bfirststage[1,1]
test z

// the F test >= 10, so it satifies the standard rule of thumb
// clustering at the category level seems reasonable

// 2. 
ivreg2 lnw (d = z), cluster(clus)
matrix biv = e(b)
matrix biv = biv[1,1]

// 3. 
// the previous exercise displays the estimate based on the IV estimator
// the two-step least squares is the folliwing

// first stage
reg d z
// obtain prediction 
predict dpredict, xb

// second stage
reg lnw dpredict
matrix btsls = e(b)
matrix btsls = btsls[1,1]

mat list biv 
mat list btsls

// which are numerically equivalent down to computer precision

// 4. 
reg lnw z, cluster(clus)
matrix breduced = e(b)
matrix breduced = breduced[1,1]

matrix bwald = breduced[1,1]/bfirststage[1,1]
mat list biv 
mat list btsls
mat list bwald

// because the lottery pushes up the probability of choice, then the direct channel 
// (effect of d on lnw) is larger than the reduced form
// the wald estimator is precisely blowed up by the increase in the take-up probability
// generated by the lottery

// only the variance in 2. is correct; the two-step estimators do not account for this
// two-step process. 
